[cki_land]
lon_range = [96.57, 96.95]
lat_range = [-12.22, -11.79]

[cki]
lon_range = [96.6, 97.1]
lat_range = [-12.3, -11.8]

[ci_land]
lon_range = [105.53, 105.72]
lat_range = [-10.58, -10.40]

[ci]
lon_range = [105.4, 105.9]
lat_range = [-10.7, -10.2]
